apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: application
      name: backend
    name: backend
  spec:
    containers:
    - name: backend
      env:
      - name: MARIADB_ROOT_PASSWORD
        value: Password123!
      - name: MARIADB_DATABASE
        value: demo
      image: quay.io/rpatel0019/db_image
      ports:
      - containerPort: 3306
        name: backend
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: backend-volume
      #command:
      #- chown
      #- -R
      #- $(whoami)
      #- /var/lib/mysql
    volumes:
    - name: backend-volume
      persistentVolumeClaim:
        claimName: backend-claim
    #initContainers:
    #- name: backend-ownership
    #  image: quay.io/rpatel0019/db_image
    #  # Give `mysql` user permissions a mounted volume
    #  # https://stackoverflow.com/a/51195446/4360433
    #  volumeMounts:
    #  - name: backend-volume
    #    mountPath: /var/lib/mysql  
        
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: application
      name: flask
    name: flask
  spec:
    containers:
    - env:
      - name: IP_ADDR
        value: ${mariadb_ip_addr}
      image: quay.io/rpatel0019/flask_image
      name: flask
      ports:
      - containerPort: 5000
        name: flask
      resources:
        limits:
          cpu: "0.5"
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: application
      name: flask
    name: flask
  spec:
    ports:
    - port: 5000
    selector: 
      name: flask
- apiVersion: v1
  kind: Service
  metadata:
    labels: 
      app: application
      name: backend
    name: backend
  spec:
    ports:
    - port: 3306
    selector:
      name: backend
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata: 
    labels: 
      app: application
    name: backend-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Mi
kind: List
metadata: {}