apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: hw3
      name: backend
    name: backend
  spec:
    containers:
    - env:
      image: quay.io/rpatel0019/db_image
      name: backend
      ports:
      - containerPort: 3306
        name: backend
      volumeMounts:
      - mountPath: /var/lib/mysql/backend
        name: backend-volume
    securityContext:
      fsGroup: 777
    volumes:
    - name: backend-volume
      persistentVolumeClaim:
        claimName: backend-claim
- apiVersion: v1
  kind: Pod
  metadata:
    labels:
      app: hw3
      name: flask
    name: flask
  spec:
    containers:
    - env:
      - name: IP_ADDR
        value: ${mariadb_ip_addr}
      image: quay.io/rpatel0019/flask_image
      name: flask
      ports:
      - containerPort: 5000
        name: flask
      resources:
        limits:
          cpu: "0.5"
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: hw3
      name: flask
    name: flask
  spec:
    ports:
    - port: 5000
    selector: 
      name: flask
- apiVersion: v1
  kind: Service
  metadata:
    labels: 
      app: hw3
      name: backend
    name: backend
  spec:
    ports:
    - port: 3306
    selector:
      name: backend
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata: 
    labels: 
      app: hw3
    name: backend-claim
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Mi
kind: List
metadata: {}